[package]
name = "mqtt_protocol"
version = "0.1.0"
authors = ["avi <avrham408@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mqtt"
path = "src/lib.rs"


[dependencies]
